CREATE VIEW MUS_OWNER.MY_MUSIC3
AS
SELECT MAR.ARTIST_NAME,
       MAL.PART_ALBUM_NAME,
       MAL.TYPE,
       MAL.GENRE,
       MAL.RELEASE_DATE
FROM   MUS_OWNER.ARTIST MAR,
       MUS_OWNER.ALBUM MAL
WHERE  MAR.ID = MAL.ARTIST_ID;
