DROP VIEW IF EXISTS MUS_OWNER.MY_MUSIC;
DROP VIEW IF EXISTS MUS_OWNER.MY_MUSIC2;
DROP VIEW IF EXISTS MUS_OWNER.MY_MUSIC3;

CREATE VIEW MUS_OWNER.MY_MUSIC2
AS
SELECT MAR.ARTIST_NAME,
       MAL.FULL_ALBUM_NAME,
       MAL.TYPE,
       MAL.GENRE,
       MAR.SPOTIFY_GENRES,
       MAL.DURATION_MIN,
       MAL.RELEASE_DATE
FROM   MUS_OWNER.ARTIST MAR,
       MUS_OWNER.ALBUM MAL
WHERE  MAR.ID = MAL.ARTIST_ID;

CREATE VIEW MUS_OWNER.MY_MUSIC3
AS
SELECT MAR.ARTIST_NAME,
       MAL.PART_ALBUM_NAME,
       MAL.TYPE,
       MAL.GENRE,
       MAR.SPOTIFY_GENRES,
       MAL.DURATION_MIN,
       MAL.RELEASE_DATE
FROM   MUS_OWNER.ARTIST MAR,
       MUS_OWNER.ALBUM MAL
WHERE  MAR.ID = MAL.ARTIST_ID;

CREATE VIEW MUS_OWNER.MY_MUSIC
AS
SELECT MA.ARTIST_NAME AS ARTIST,
       MR.FULL_ALBUM_NAME AS ALBUM,
       MA.SPOTIFY_GENRES,
       MR.DURATION_MIN,
       MR.RELEASE_DATE AS "RELEASE DATE"
FROM   MUS_OWNER.ARTIST MA, 
       MUS_OWNER.ALBUM MR 
WHERE  MA.ID = MR.ARTIST_ID
ORDER  BY 1,3,2;

