ALTER TABLE MUS_OWNER.ARTIST
ADD COLUMN SPOTIFY_GENRES TEXT[];

UPDATE MUS_OWNER.ARTIST MA
SET    SPOTIFY_GENRES = (SELECT SPOTIFY_GENRES FROM MUS_OWNER.ALBUM ML WHERE MA.ID = ML.ARTIST_ID LIMIT 1);

ALTER TABLE MUS_OWNER.ALBUM
DROP COLUMN SPOTIFY_GENRES CASCADE;
